repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: pretty-format-json
        args: ["--autofix"]
      - id: mixed-line-ending
        args: ["--fix=lf"]
        description: Forces to replace line ending by the UNIX 'lf' character.
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=5000']
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.6
    hooks:
      # Run the linter and fix issues immediately when possible.
      # NOTE needs to run *before* the formatter and other tools like isort
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      # Run the Black-compatible formatter.
      - id: ruff-format
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
  - repo: local
    hooks:
      # Pylint will gave more elaborate warnings, but do not fail commit
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        verbose: true
        args:
          [
            "--rcfile=.pylintrc",
            "--exit-zero",
          ]
