version: '1'
services:
  devcontainer:
    build: .
    stdin_open: true  # docker run -i
    tty: true         # docker run -t
    volumes:
      - home:/home/edwin
    env_file:
      - .env
volumes:
  home:
